---
title: "Datos Huawei"
output:
  html_document: default
  pdf_document: default
---
#LIMPIEZA DE DATOS DE LA MARCA HUAWEI 

#Gerardo Gutiérrez Aguirre			    A01368146
#Juan Ramón Rodríguez Márquez       A01365002
#José Manuel González Guadarrama	  A01364681
#Kevin Alberto Sorzano Mongel	    	A01368603
#Mario Naime Monroy                 A01365605
#José Alberto Naime Monroy          A01365892



```{r}
library(tidyverse)
library(readr)
```
```{r}
#file.choose()
```
```{r}
datoshuawei <- read.csv( "/Users/gerardogutierrez/Downloads/APUNTES TEC/Lab. de diseño y opt. de operaciones/Proyecto/equipo_5_huawei_datos_sucios.csv") 
#datoshuawei
```

```{r}
#RESUMEN DATOS 

summary(datoshuawei)
```

```{r}
#CAMBIO PUNTO DE VENTA

datoshuawei$punto_de_venta <- tolower(datoshuawei$punto_de_venta)


datoshuawei$punto_de_venta <- str_replace(datoshuawei$punto_de_venta, "1poniente", "1 poniente") %>%
  str_replace("ace alhondga", "ace alhondiga") %>%
  str_replace("acr centroapizacotl", "ace centroapizacotl") %>% 
  str_replace("aacr centroapizacotl", "ace centroapizacotl") %>% 
  str_replace("acr leon centro gto", "ace leon centro gto") %>% 
  str_replace("aace centroapizacotl", "ace centroapizacotl") %>% 
  str_replace("acr atlixcocentropue", "ace atlixcocentropue") %>% 
  str_replace("ars nuevo sur mty", "arsa nuevo sur mty") %>% 
  str_replace("á", "a") %>%
  str_replace("é", "e") %>%
  str_replace("í", "i") %>%
  str_replace("o", "o") %>%
  str_replace("ú", "u")

datoshuawei %>% select(punto_de_venta) %>% unique()
```

```{r}
#CAMBIO MES

datoshuawei$mes <- str_replace(datoshuawei$mes, "JUN", "6") %>%
  str_replace("JUL", "7") %>%
  str_replace("SEPT ", "9") %>%
  str_replace("SEPT", "9") %>%
  str_replace("DIC", "12") %>%
  str_replace("MAR", "3")
datoshuawei$mes <- as.numeric(datoshuawei$mes)
datoshuawei %>% select(mes) %>% unique()
```

```{r}
#CAMBIO AÑO

datoshuawei$anio <- str_replace(datoshuawei$anio, "18", "2018") %>%
  str_replace("202018", "2018")
datoshuawei %>% select(anio) %>% unique()
```

```{r}
#CAMBIO MARCA 

datoshuawei$marca <- tolower(datoshuawei$marca)
datoshuawei$marca <- str_replace(datoshuawei$marca, "hhuawei", "huawei")
datoshuawei$marca <- str_replace(datoshuawei$marca, "huawei-huawei", "huawei")
datoshuawei %>% select(marca) %>% unique()
```

```{r}
#CAMBIO ZONA

datoshuawei$zona <- tolower(datoshuawei$zona)
datoshuawei %>% select(zona) %>% unique()
```

```{r}
#CAMBIO ESTADO

datoshuawei$estado <- str_replace(datoshuawei$estado, "metepec", "estado de mexico")
datoshuawei$estado <- str_replace(datoshuawei$estado, "la paz", "baja california sur")
datoshuawei$estado <- str_replace(datoshuawei$estado, "merida", "yucatan")
datoshuawei %>% select(estado) %>% unique()
```

```{r}
#CAMBIO LATITUD

which(datoshuawei$latitud > 40)
datoshuawei[27828,13] <- 19.41515
summary(datoshuawei$latitud) #Máximo gigante
```

```{r}
#CAMBIO LONGITUD

which(datoshuawei$longitud < -150)
datoshuawei[27828,14] <- -99.49052 
summary(datoshuawei$longitud) #Mínimo gigante
```
